package;

using api.IdeckiaApi;

typedef Props = {
	@:editable("Property description", "default value", ["possible", "values", "for the property"])
	var property_name:String;
}

@:name("::name::")
@:description("::description::")
class ::className:: extends IdeckiaAction {
	override public function init(initialState:ItemState):js.lib.Promise<ItemState>
		return super.init(initialState);

	public function execute(currentState:ItemState):js.lib.Promise<ActionOutcome> {
        return js.lib.Promise.reject('Not implemented');
        // return js.lib.Promise.resolve(new ActionOutcome({state: currentState}));
	}

	override public function onLongPress(currentState:ItemState):js.lib.Promise<ActionOutcome>
		return super.onLongPress(currentState);

	override public function getStatus():js.lib.Promise<ActionStatus>
		return super.getStatus();

	override public function show(currentState:ItemState):js.lib.Promise<ItemState>
		return super.show(currentState);

	override public function hide():Void {}

	// AUTOGENERATED
	/*
		var props:Props;
		var server:IdeckiaServer;

		public function setup(props:Any, ?server:IdeckiaServer) {
			this.props = props;
			this.server = server;
		}

		public function getActionDescriptor():js.lib.Promise<ActionDescriptor> {
			return js.lib.Promise.resolve({
				name : "::name::",
				description : "::description::",
				props : [{
					name : "property_name",
					defaultValue: "default value",
					type: "String",
					value: "possible",
					isShared: false,
					description : "property description",
					values : ["possible", "values", "for the property"]
				}]
			}));
		}
	 */
}
